export const PRODUCT_POST_REQUEST = "PRODUCT_POST_REQUEST"
export const PRODUCT_POST_SUCCESS = "PRODUCT_POST_SUCCESS"
export const PRODUCT_POST_FAIL = "PRODUCT_POST_FAIL"

export const PRODUCT_DELETE_REQUEST = "PRODUCT_DELETE_REQUEST"
export const PRODUCT_DELETE_SUCCESS = "PRODUCT_DELETE_SUCCESS"
export const PRODUCT_DELETE_FAIL = "PRODUCT_DELETE_FAIL"

